import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Contact() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
          <h1 className={styles.title}>Contact</h1>
      </div>
    )
  }