import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';

import Header from '../components/Header';
import Grid from '../components/Grid';
import Card from '../components/Card';
import Carousel from '../components/Carousel';
import List from '../components/List';
import Marquee from '../components/Marquee';

import styles from '../styles/Home.module.css'

const plants = [
    { title: 'Achillea Moonshine', description: 'Lorem ipsum'},
    { title: 'Agastache' }
];

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Hello world</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <Image
                className={styles.image}
                src='/images/geranium.webp'
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                height={250}
                width={500}
                alt='Geranium rozanne'
            />

            <Marquee />

            <p className={styles.lead}>
                <span>Geranium &lsquo;Rozanne&rsquo;.</span> Hybrid of Geranium himalayense and Geranium wallichianum &lsquo;Buxton&apos;s variety&rsquo;.
            </p>

            <List items={plants} />

            <Grid columns={2}>
                <div>Drift, group, border, flower meadow. Praerie. Clump-forming ground cover. Variegated foliage.</div>

                <div>Test 2</div>
            </Grid>

            <Carousel />
            
            <Grid columns={4} columnsSm={2}>
                <Card>
                    <h2>
                        90cm
                    </h2>
                    Drift, group, border, flower meadow. Praerie. Clump-forming ground cover. Variegated foliage.
                </Card>
                <Card>
                    <h2>
                        90cm
                    </h2>
                    Drift, group, border, flower meadow. Praerie. Clump-forming ground cover. Variegated foliage.
                </Card>
                <Card>
                    <h2>
                        90cm
                    </h2>
                    Drift, group, border, flower meadow. Praerie. Clump-forming ground cover. Variegated foliage.
                </Card>
                <Card>
                    <h2>
                        90cm
                    </h2>
                    Drift, group, border, flower meadow. Praerie. Clump-forming ground cover. Variegated foliage.
                </Card>
            </Grid>
        </div>
    )
}
